server:
  port: 18081
spring:
  application:
    name: user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
  redis:
    host: 127.0.0.1


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml